<?php

namespace AppBundle\Repository;

/**
 * ViceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViceRepository extends \Doctrine\ORM\EntityRepository
{
}
